version: '3.3'
services:
  api:
    image: 'jormae/welfare-api:1.3.0'
    environment:
      HOST_NAME: ${HOST_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    build:  .
    ports:
      - 3030:3030
    restart: always